// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Rm9fbtD-J6W6uaOwdttRK3GQwPklC6A',
    appId: '1:950564714045:android:e7d30a109958444fa39c54',
    messagingSenderId: '950564714045',
    projectId: 'tnennt-1e1f2',
    storageBucket: 'tnennt-1e1f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-PhHgJFYQ8Ndwbyv7TAWLmg0FNlEPjvg',
    appId: '1:950564714045:ios:00439150f874a534a39c54',
    messagingSenderId: '950564714045',
    projectId: 'tnennt-1e1f2',
    storageBucket: 'tnennt-1e1f2.appspot.com',
    androidClientId:
        '950564714045-5nuorc4ghg3e9859gnbmlukj99fsakm5.apps.googleusercontent.com',
    iosClientId:
        '950564714045-fq5s9nh6rp287996fmajlgk096qv1mcc.apps.googleusercontent.com',
    iosBundleId: 'com.tnent.tnent',
  );
}
